site_name: 'My Data Story'
nav:
  - Introduction: introduction.md
  - Analysis: analysis.md
  - Conclusions: conclusions.md



theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/logo.png   # optional, if you have a logo
extra_css:
  - css/custom.css        # optional, for your overrides
